
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-app
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080